#!/bin/sh

docker-compose exec kafka \
kafka-topics --create --topic $1 --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:2181

docker-compose exec kafka \
kafka-configs --zookeeper localhost:2181 --entity-type topics --alter --entity-name $1 --add-config retention.ms=25
